### ISSUE TITLE
Check version

### ISSUE THREAD

**Issue by sinhzun** [suicao/PhoBert-Sentiment-Classification#2]
Hi bạn, mình run thử code thì thấy báo lỗi `NameError: name 'ALBERT_PRETRAINED_MODEL_ARCHIVE_MAP' is not defined`
Khả năng do khác version của transformer. Bạn dùng version nào vậy?

**Comment by suicao** [comment]
Mình update code cho models.py để đúng với huggingface bản mới rồi nhé bạn
